name: Bug report
description: Reporte um problema
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Descreva o problema observado.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos para reproduzir o erro.
      placeholder: "1. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Navegador, sistema operacional, versão.
